services:
  backend:
    build:
      context: ./voice-coach-backend
    ports:
      - "8000:8000"
    volumes:
      - ./voice-coach-backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./voice-coach-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./voice-coach-frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend